CREATE TABLE USERS (
    USERNAME TEXT NOT NULL PRIMARY KEY,
    PASSWORD TEXT NOT NULL,
    ENABLED BOOLEAN NOT NULL
);

CREATE TABLE AUTHORITIES (
    USERNAME TEXT NOT NULL,
    AUTHORITY TEXT NOT NULL,
    CONSTRAINT FK_AUTHORITIES_USERS FOREIGN KEY(USERNAME) REFERENCES USERS(USERNAME)
);
